name: iOS Build - RUNTIME IDENTIFIERS FIXED

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ios:
    runs-on: macos-14
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

      - name: Setup .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Environment Diagnostics
        run: |
          echo "=== .NET Environment ==="
          dotnet --info
          echo "=== Xcode Environment ==="
          xcodebuild -version
          xcrun --show-sdk-path --sdk iphonesimulator
          echo "=== iOS Simulators ==="
          xcrun simctl list devices ios --json | jq '.devices | to_entries[] | select(.key | contains("iOS")) | {version: .key, devices: .value}'

      - name: Clean Previous Builds
        run: |
          cd HelloMaui
          dotnet clean
          rm -rf bin/ obj/

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui --skip-sign-check --source https://api.nuget.org/v3/index.json
          dotnet workload list

      - name: Restore Dependencies with iOS Focus
        run: |
          cd HelloMaui
          dotnet restore HelloMaui.csproj -f net8.0-ios -v detailed

      - name: Build iOS Release with RuntimeIdentifier
        run: |
          cd HelloMaui
          echo "=== Building iOS Release for iossimulator-x64 ==="
          dotnet build HelloMaui.csproj \
            -f net8.0-ios \
            -c Release \
            -r iossimulator-x64 \
            -p:UseInterpreter=true \
            -p:MtouchDebug=false \
            -p:MtouchFastDev=false \
            -v detailed
          
          # Check if build succeeded
          if [ $? -eq 0 ]; then
            echo " Release build succeeded"
            ls -la bin/Release/net8.0-ios/iossimulator-x64/
          else
            echo " Release build failed, trying Debug build"
            dotnet build HelloMaui.csproj \
              -f net8.0-ios \
              -c Debug \
              -r iossimulator-x64 \
              -p:UseInterpreter=true \
              -p:MtouchDebug=true \
              -p:MtouchFastDev=true \
              -v detailed
          fi

      - name: Upload iOS Build Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: HelloMaui-iOS-Build-Output
          path: |
            HelloMaui/bin/**/net8.0-ios/**/*
            HelloMaui/obj/**/net8.0-ios/**/*.assets.json
          retention-days: 7

      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: HelloMaui-iOS-Build-Logs
          path: |
            **/*.binlog
            **/*.log
          retention-days: 3
