name: iOS Build - WORKLOAD INSTALLATION FIXED

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ios:
    runs-on: macos-14
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

      - name: Setup .NET 8.0.x (Specific Version)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.413'
          
      - name: Verify .NET Installation
        run: |
          echo "=== .NET Version Check ==="
          dotnet --version
          dotnet --info
          echo "=== Pre-Workload Check ==="
          dotnet workload list

      - name: Install .NET MAUI Workloads (CRITICAL FIX)
        run: |
          echo "=== Installing MAUI Workloads ==="
          dotnet workload install maui --skip-sign-check --source https://api.nuget.org/v3/index.json --verbosity detailed
          echo "=== Post-Installation Verification ==="
          dotnet workload list
          echo "=== Workload Installation Complete ==="

      - name: Environment Diagnostics
        run: |
          echo "=== Xcode Environment ==="
          xcodebuild -version
          xcrun --show-sdk-path --sdk iphonesimulator
          echo "=== iOS Simulators Available ==="
          xcrun simctl list devices ios --json | jq '.devices | keys[]' | head -5

      - name: Clean and Prepare Build
        run: |
          cd HelloMaui
          echo "=== Cleaning Previous Build ==="
          rm -rf bin/ obj/
          echo "=== Project File Contents ==="
          cat HelloMaui.csproj

      - name: Restore Dependencies
        run: |
          cd HelloMaui
          echo "=== Restoring All Dependencies ==="
          dotnet restore HelloMaui.csproj --verbosity detailed
          echo "=== iOS-Specific Restore ==="
          dotnet restore HelloMaui.csproj -f net8.0-ios --verbosity detailed

      - name: Build iOS Release
        run: |
          cd HelloMaui
          echo "=== Building iOS for Simulator ==="
          dotnet build HelloMaui.csproj \
            -f net8.0-ios \
            -c Release \
            -r iossimulator-x64 \
            -p:UseInterpreter=true \
            -p:MtouchDebug=false \
            -p:MtouchFastDev=false \
            --verbosity detailed
          
          echo "=== Build Output Check ==="
          find bin/ -name "*.app" -type d 2>/dev/null || echo "No .app files found"
          find bin/ -type f -name "*.dll" | head -5 || echo "No .dll files found"

      - name: Build iOS Debug (Fallback)
        if: failure()
        run: |
          cd HelloMaui
          echo "=== Fallback: Building iOS Debug ==="
          dotnet build HelloMaui.csproj \
            -f net8.0-ios \
            -c Debug \
            -r iossimulator-x64 \
            -p:UseInterpreter=true \
            -p:MtouchDebug=true \
            -p:MtouchFastDev=true \
            --verbosity detailed

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: HelloMaui-iOS-Build-Complete
          path: |
            HelloMaui/bin/**/*
            HelloMaui/obj/**/*.assets.json
          retention-days: 7

      - name: Upload Logs and Diagnostics
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: HelloMaui-Build-Diagnostics
          path: |
            **/*.log
            **/*.binlog
          retention-days: 3
